'use server'

import { headers } from 'next/headers'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { sendInvitationEmail } from '@/lib/email/invitation'
import { track } from '@/lib/analytics/track'

export interface CreateInvitationInput {
    organizationId: string
    email: string
    role: 'admin' | 'staff'
}

export type CreateInvitationResult =
    | { ok: true; invitationId: string; emailSent: boolean }
    | { ok: false; error: string }

async function getOrigin(): Promise<string> {
    try {
        const h = await headers()
        const proto = h.get('x-forwarded-proto') ?? 'https'
        const host = h.get('x-forwarded-host') ?? h.get('host')
        if (host) return `${proto}://${host}`
    } catch {}
    return process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
}

export async function createInvitationAction(
    input: CreateInvitationInput
): Promise<CreateInvitationResult> {
    const { organizationId, email: rawEmail, role } = input
    const email = rawEmail.trim().toLowerCase()

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        return { ok: false, error: 'Please enter a valid email address.' }
    }
    if (!['admin', 'staff'].includes(role)) {
        return { ok: false, error: 'Role must be admin or staff.' }
    }

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return { ok: false, error: 'You must be logged in.' }
    }

    const service = createServiceClient()

    // Verify caller is admin/owner of this org
    const { data: membership } = await service
        .from('organization_members')
        .select('role')
        .eq('organization_id', organizationId)
        .eq('user_id', user.id)
        .single()

    if (!membership || !['owner', 'admin'].includes(membership.role)) {
        return { ok: false, error: 'You do not have permission to invite members to this organization.' }
    }

    // Check for existing invitation (UNIQUE constraint on org_id + email)
    const { data: existing } = await service
        .from('organization_invitations')
        .select('id, accepted_at, expires_at')
        .eq('organization_id', organizationId)
        .eq('email', email)
        .single()

    if (existing) {
        if (existing.accepted_at) {
            return { ok: false, error: 'This email has already accepted an invitation.' }
        }
        if (new Date(existing.expires_at) < new Date()) {
            await service.from('organization_invitations').delete().eq('id', existing.id)
        } else {
            return { ok: false, error: 'A pending invitation already exists for this email.' }
        }
    }

    // Get org name for email
    const { data: org } = await service
        .from('organizations')
        .select('name')
        .eq('id', organizationId)
        .single()

    if (!org) {
        return { ok: false, error: 'Organization not found.' }
    }

    // Insert invitation (token auto-generated by DB default)
    const { data: invitation, error: insertError } = await service
        .from('organization_invitations')
        .insert({
            organization_id: organizationId,
            email,
            role,
            invited_by: user.id,
        })
        .select('id, token')
        .single()

    if (insertError || !invitation) {
        return { ok: false, error: `Could not create invitation: ${insertError?.message ?? 'unknown error'}` }
    }

    const origin = await getOrigin()
    const inviteUrl = `${origin}/invite/${invitation.token}`

    const emailResult = await sendInvitationEmail({
        toEmail: email,
        orgName: org.name,
        role,
        inviteUrl,
    })

    if (emailResult.success) {
        track('invitation_email_sent', {
            organization_id: organizationId,
            invitation_id: invitation.id,
        })
    }

    return {
        ok: true,
        invitationId: invitation.id,
        emailSent: emailResult.success,
    }
}

export async function revokeInvitationAction(
    invitationId: string
): Promise<{ ok: true } | { ok: false; error: string }> {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return { ok: false, error: 'You must be logged in.' }
    }

    const service = createServiceClient()

    const { data: invitation } = await service
        .from('organization_invitations')
        .select('organization_id, accepted_at')
        .eq('id', invitationId)
        .single()

    if (!invitation) {
        return { ok: false, error: 'Invitation not found.' }
    }
    if (invitation.accepted_at) {
        return { ok: false, error: 'Cannot revoke an accepted invitation.' }
    }

    const { data: membership } = await service
        .from('organization_members')
        .select('role')
        .eq('organization_id', invitation.organization_id)
        .eq('user_id', user.id)
        .single()

    if (!membership || !['owner', 'admin'].includes(membership.role)) {
        return { ok: false, error: 'You do not have permission to revoke invitations.' }
    }

    const { error } = await service
        .from('organization_invitations')
        .delete()
        .eq('id', invitationId)

    if (error) {
        return { ok: false, error: `Could not revoke invitation: ${error.message}` }
    }

    return { ok: true }
}
